// Example partial list - you can expand this
export const KNOWN_COMMODITIES = [
    "Agronomic Treatment",
    "Explosives",
    "Hydrogen Fuel",
    "Hydrogen Peroxide",
    "Liquid Oxygen",
    "Mineral Oil",
    "Nerve Agents",
    "Pesticides",
    "Rockforth Fertiliser",
    "Surface Stabilisers",
    "Synthetic Reagents",
    "Tritium",
    "Water",
    "Consumer Items",
    "Clothing",
    "Consumer Technology",
    "Domestic Appliances",
    "Evacuation Shelter",
    "Survival Equipment",
    "Legal Drugs",
    "Beer",
    "Bootleg Liquor",
    "Liquor",
    "Narcotics",
    "Onionhead Gamma Strain",
    "Tobacco",
    "Wine",
    "Foods",
    "Algae",
    "Animal Meat",
    "Coffee",
    "Fish",
    "Food Cartridges",
    "Fruit And Vegetables",
    "Grain",
    "Synthetic Meat",
    "Tea",
    "Industrial Materials",
    "Ceramic Composites",
    "Cmm Composite",
    "Insulating Membrane",
    "Meta-alloys",
    "Micro-weave Cooling Hoses",
    "Neofabric Insulation",
    "Polymers",
    "Semiconductors",
    "Superconductors",
    "Machinery",
    "Articulation Motors",
    "Atmospheric Processors",
    "Building Fabricators",
    "Crop Harvesters",
    "Emergency Power Cells",
    "Energy Grid Assembly",
    "Exhaust Manifold",
    "Geological Equipment",
    "Heatsink Interlink",
    "Hn Shock Mount",
    "Ion Distributor",
    "Magnetic Emitter Coil",
    "Marine Equipment",
    "Microbial Furnaces",
    "Mineral Extractors",
    "Modular Terminals",
    "Power Converter",
    "Power Generators",
    "Power Transfer Bus",
    "Radiation Baffle",
    "Reinforced Mounting Plate",
    "Skimmer Components",
    "Thermal Cooling Units",
    "Water Purifiers",
    "Medicines",
    "Advanced Medicines",
    "Agri-medicines",
    "Basic Medicines",
    "Combat Stabilisers",
    "Performance Enhancers",
    "Progenitor Cells",
    "Metals",
    "Aluminium",
    "Beryllium",
    "Bismuth",
    "Cobalt",
    "Copper",
    "Gallium",
    "Gold",
    "Hafnium",
    "Indium",
    "Lanthanum",
    "Lithium",
    "Osmium",
    "Palladium",
    "Platinum",
    "Praseodymium",
    "Samarium",
    "Silver",
    "Steel",
    "Tantalum",
    "Thallium",
    "Thorium",
    "Titanium",
    "Uranium",
    "Minerals",
    "Alexandrite",
    "Bauxite",
    "Benitoite",
    "Bertrandite",
    "Bromellite",
    "Coltan",
    "Cryolite",
    "Gallite",
    "Goslarite",
    "Grandidierite",
    "Haematite",
    "Indite",
    "Jadeite",
    "Lepidolite",
    "Lithium Hydroxide",
    "Low Temperature Diamonds",
    "Methane Clathrate",
    "Methanol Monohydrate Crystals",
    "Moissanite",
    "Monazite",
    "Musgravite",
    "Painite",
    "Pyrophyllite",
    "Rhodplumsite",
    "Rutile",
    "Serendibite",
    "Taaffeite",
    "Uraninite",
    "Void Opal",
    "Salvage",
    "Ai Relics",
    "Ancient Artefact",
    "Ancient Key",
    "Anomaly Particles",
    "Antimatter Containment Unit",
    "Antique Jewellery",
    "Antiquities",
    "Assault Plans",
    "Black Box",
    "Bone Fragments",
    "Caustic Tissue Sample",
    "Commercial Samples",
    "Coral Sap",
    "Cyst Specimen",
    "Damaged Escape Pod",
    "Data Core",
    "Diplomatic Bag",
    "Earth Relics",
    "Encrypted Correspondence",
    "Encrypted Data Storage",
    "Experimental Chemicals",
    "Fossil Remnants",
    "Gene Bank",
    "Geological Samples",
    "Guardian Casket",
    "Guardian Orb",
    "Guardian Relic",
    "Guardian Tablet",
    "Guardian Totem",
    "Guardian Urn",
    "Hostages",
    "Impure Spire Mineral",
    "Large Survey Data Cache",
    "Military Intelligence",
    "Military Plans",
    "Mollusc Brain Tissue",
    "Mollusc Fluid",
    "Mollusc Membrane",
    "Mollusc Mycelium",
    "Mollusc Soft Tissue",
    "Mollusc Spores",
    "Mysterious Idol",
    "Occupied Escape Pod",
    "Organ Sample",
    "Personal Effects",
    "Pod Core Tissue",
    "Pod Dead Tissue",
    "Pod Mesoglea",
    "Pod Outer Tissue",
    "Pod Shell Tissue",
    "Pod Surface Tissue",
    "Pod Tissue",
    "Political Prisoners",
    "Precious Gems",
    "Prohibited Research Materials",
    "Protective Membrane Scrap",
    "Prototype Tech",
    "Rare Artwork",
    "Rebel Transmissions",
    "Sapcore Container",
    "Scientific Research",
    "Scientific Samples",
    "Semi-refined Spire Mineral",
    "Small Survey Data Cache",
    "Space Pioneer Relics",
    "Tactical Data",
    "Technical Blueprints",
    "Thargoid Basilisk Tissue Sample",
    "Thargoid Bio-storage Capsule",
    "Thargoid Biological Matter",
    "Thargoid Cyclops Tissue Sample",
    "Thargoid Glaive Tissue Sample",
    "Thargoid Heart",
    "Thargoid Hydra Tissue Sample",
    "Thargoid Link",
    "Thargoid Medusa Tissue Sample",
    "Thargoid Orthrus Tissue Sample",
    "Thargoid Probe",
    "Thargoid Resin",
    "Thargoid Scout Tissue Sample",
    "Thargoid Scythe Tissue Sample",
    "Thargoid Sensor",
    "Thargoid Technology Samples",
    "Time Capsule",
    "Titan Deep Tissue Sample",
    "Titan Drive Component",
    "Titan Maw Deep Tissue Sample",
    "Titan Maw Partial Tissue Sample",
    "Titan Maw Tissue Sample",
    "Titan Partial Tissue Sample",
    "Titan Tissue Sample",
    "Trade Data",
    "Trinkets Of Hidden Fortune",
    "Unclassified Relic",
    "Unoccupied Escape Pod",
    "Unstable Data Core",
    "Wreckage Components",
    "Slaves",
    "Imperial Slaves",
    "Slaves",
    "Technology",
    "Advanced Catalysers",
    "Animal Monitors",
    "Aquaponic Systems",
    "Auto-fabricators",
    "Bioreducing Lichen",
    "Computer Components",
    "H.e. Suits",
    "Hardware Diagnostic Sensor",
    "Land Enrichment Systems",
    "Medical Diagnostic Equipment",
    "Micro Controllers",
    "Muon Imager",
    "Nanobreakers",
    "Resonating Separators",
    "Robotics",
    "Structural Regulators",
    "Telemetry Suite",
    "Textiles",
    "Conductive Fabrics",
    "Leather",
    "Military Grade Fabrics",
    "Natural Fabrics",
    "Synthetic Fabrics",
    "Waste",
    "Biowaste",
    "Chemical Waste",
    "Scrap",
    "Toxic Waste",
    "Weapons",
    "Battle Weapons",
    "Landmines",
    "Non-lethal Weapons",
    "Personal Weapons",
    "Reactive Armour"
];